local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "Mark a file for quick access" })
vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu, { desc = "Open the list of accessible files" })

vim.keymap.set("n", "<c-s-right>", function()
	ui.nav_next()
end, { desc = "Move to the next harpoon file" })

vim.keymap.set("n", "<c-s-left>", function()
	ui.nav_prev()
end, { desc = "Move to the previous harpoon file" })

vim.keymap.set("n", "<leader>1", function()
	ui.nav_file(1)
end, { desc = "Move to the 1st harpoon file" })
vim.keymap.set("n", "<leader>2", function()
	ui.nav_file(2)
end, { desc = "Move to the 2nd harpoon file" })
vim.keymap.set("n", "<leader>3", function()
	ui.nav_file(3)
end, { desc = "Move to the 3rd harpoon file" })
vim.keymap.set("n", "<leader>4", function()
	ui.nav_file(4)
end, { desc = "Move to the 4th harpoon file" })
vim.keymap.set("n", "<leader>5", function()
	ui.nav_file(5)
end, { desc = "Move to the 5th harpoon file" })
