local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pp", builtin.find_files, {})
vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>pd", builtin.diagnostics, {})
vim.keymap.set("n", "<leader>pb", builtin.buffers, {})
vim.keymap.set("n", "<leader>pt", builtin.treesitter, {})
vim.keymap.set("n", "<leader>lr", builtin.lsp_references, {})
vim.keymap.set("n", "<leader>pS", function()
	builtin.grep_string({ search = vim.fn.input("Grep > "), use_regex = true })
end, {})
vim.keymap.set("n", "<leader>ps", builtin.live_grep, {})
vim.keymap.set("v", "<leader>ps", function()
	builtin.grep_string({ search = vim.getVisualSelection() })
end, {})

vim.keymap.set("n", "<leader>vd", function()
	builtin.diagnostics({ buffer = 0 })
end, {})
