vim.keymap.set("n", "<c-h>", vim.cmd.TmuxNavigateLeft, { desc = "Move left between vim panes" })
vim.keymap.set("n", "<c-j>", vim.cmd.TmuxNavigateDown, { desc = "Move down between vim panes" })
vim.keymap.set("n", "<c-k>", vim.cmd.TmuxNavigateUp, { desc = "Move up between vim panes" })
vim.keymap.set("n", "<c-l>", vim.cmd.TmuxNavigateRight, { desc = "Move right between vim panes" })
vim.keymap.set("n", "<c-\\>", vim.cmd.TmuxNavigatePrevious, { desc = "Move to the last vim pane" })
